version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: mi_redis_server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    
  mi-api-game:
    build:
      context: ./Springboot/proyectoBAE       
      dockerfile: Dockerfile
    container_name: mi_springboot_app
    ports:
      - "8080:8080"    
    environment:
      - SPRING_DATA_REDIS_HOST=redis
    depends_on:
      - redis          
    restart: always
volumes:
  redis_data:
